Upgrade deps
BlackMIDIDevs/wasabi pull request #35
Opened 2023-04-24 17:08 UTC by StratusFearMe21

Simply upgrades all of this crate's dependencies to their latest versions

2023-04-24 17:10 UTC, StratusFearMe21 commented
P.S, this PR merges #33

2023-04-25 12:32 UTC, arduano requested changes
Everything else lgtm

2023-04-25 12:32 UTC, arduano commented on Cargo.toml
> +glidesort = "0.1.2"
Do we really need this? It's used to sort a single 256 item array each frame, `sort_unstable_by_key` should be enough for that.

2023-04-25 17:02 UTC, arduano approved these changes
Everything else lgtm

2023-04-25 17:02 UTC, merged