Add NPS & Polyphony stats
BlackMIDIDevs/wasabi pull request #76
Opened 2024-10-17 19:31 UTC by MyBlackMIDIScore

Haven't figured out how to do polyphony for cake yet

Also I am not 100% sure about the NPS implementation, if there is a better way to do it lmk

2024-10-22 11:29 UTC, arduano requested changes

2024-10-22 11:29 UTC, arduano commented on src/gui/window/stats.rs
> +pub struct NpsCounter(VecDeque<(Instant, i64)>);
I prefer a field for this even if it's just a single field, more descriptive. Tuple structs are only good for very very primitive wrappers around stuff. This is more complex.

2024-10-22 11:29 UTC, arduano commented on src/gui/window/stats.rs
> +        let old = if let Some(front) = self.0.front() {
```suggestion
        let old = if let Some((front_time, passed)) = self.0.front() {
```
better than using tuples directly

2024-10-22 11:29 UTC, arduano commented on src/gui/window/scene/note_list_system/mod.rs
> +                    let out_data = columns_view_info.par_iter_mut().rev().map(|column| {
this is getting complex enough where I think a struct is better. Define a simple struct somewhere above, use it here to pass the data back.

2024-10-22 11:29 UTC, arduano commented on src/gui/window/fps.rs
> +pub struct Fps(VecDeque<Instant>);
Use named field pls

2024-11-24 16:53 UTC, MyBlackMIDIScore commented
Oh oops, I forgot about this too

Btw should we release 1.0 and leave #74 and #75 for later or should we fix those first?

2024-11-24 16:53 UTC, merged

2024-11-24 22:47 UTC, arduano commented
Yeah 1.0 now is ok